# FabricIQ — Streamlit Secrets
# Pre-configured with your Google Drive File IDs

[gdrive]
fae_best                   = "1WuEg8OTT2xgHalyJdvKJkWuz81lYit_t"
fae_mu                     = "1fjVOxhMTNtKtthtQLrGSe51SGN_zj0wq"
fae_sig                    = "1aSGFE6IksBDkOIsNvKlWavC_5A-M-dsz"
mobilenet_v3_small_recon   = "1pq3jUwdpJpjMnvVny4FAtXo81zkwb789"
mobilenet_v3_small_selfsup = "1ArFgCrWWJLsVXaFQGamQk-6c4Sc7KmIe"
efficientnet_b0_recon      = "1FkT6k8f1Ee2xbZIbIDZQLhRJjTaaRpKa"
efficientnet_b0_selfsup    = "1iItsO_jOh1axpdXmTqcJ_fncPjaubIQ2"
